=== Alexe23b/Java-Course-Mart-2016/files/in/bookstore.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!ELEMENT bookstore (section+)>
        <!ELEMENT section (book*)>
        <!ATTLIST section name CDATA #REQUIRED number ID #REQUIRED>
        <!ELEMENT book (title+,author+,publisher?,year?)>
        <!ATTLIST book id ID #REQUIRED>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT author (#PCDATA)>
        <!ELEMENT publisher (#PCDATA)>
        <!ELEMENT year (#PCDATA)>
        <!ELEMENT year3 (#PCDATA)>

=== Alexe23b/Java-Course-Mart-2016/files/in/bookstore.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookstore SYSTEM "/home/mda/Projects/MDA/Algorithms/JavaCourse_07.03.2016/files/source/bookstore.dtd">
<bookstore>
    <section name="Manuals" number="1">
        <book id="1">
            <title>Thinking in Java, 2nd Edition</title>
            <author>Bruce Ekkel</author>
            <publisher>Oâ€™Reilly</publisher>
            <year>2000</year>
        </book>
        <book id="2">
            <title>Delphi 5</title>
            <author>S. Bobrovskij</author>
            <publisher>Piter</publisher>
            <year>2000</year>
        </book>
    </section>
</bookstore>
